sudo: required
dist: trusty

before_install:
  - echo "before install"
  - pyenv global 3.6.3

install:
  - echo "install build environment"
  - pip3 install coverage

script:
  - echo "start build"
  - coverage run python/test/OpenSubscribe_unitTest.py
  - coverage report -m

after_success:
  - echo "after_success"
