sudo: required
dist: trusty

before_install:
  - echo "before install"

install:
  - echo "before install"

script:
  - echo "start build"
  - python3 python/test/OpenSubscribe_unitTest.py

after_success:
  - echo "after_success"
