sudo: required
dist: trusty

before_install:
  - echo "before install"

install:
  - echo "install build environment"
  - sudo pip install coverage

script:
  - echo "start build"
  - coverage run -m python/test/OpenSubscribe_unitTest.py
  - coverage report -m

after_success:
  - echo "after_success"
